import Head from "@/Components/Head";
import "./globals.css";
import Main from "@/Components/Main";
import Footer from "@/Components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen bg-white flex flex-col  py-4">
          <Head />
          <Main />
          {children}
          <Footer />
          <div className="py-8 text-center w-full text-slate-600">
            Copyright 2021 HLS
          </div>
        </div>
      </body>
    </html>
  );
}
